[package]
name = "melwallet-client"
version = "0.1.0"
authors = ["Themelio Labs"]
edition = "2018"

description = "melwalletd client library"
license = "MPL-2.0"
repository = "https://github.com/themeliolabs/melwallet-client"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# tmelcrypt = { git = "https://github.com/themeliolabs/themelio-core" }
tmelcrypt= "0.1.0"
smolscale= "0.3.11"
stdcode= "0.1.2"
themelio-stf= "0.4.3"
serde={ version = "1.0.126", features = ["derive"] }
anyhow= "1.0.41"
tracing-subscriber = "0.2.19"
log= "0.4.14"
tracing= "0.1.26"
smol= "1.2.5"
serde_json= { version = "1.0.64", features = ["arbitrary_precision"] }
structopt= "0.3.21"
async-h1= "2.3.2"
dirs= "3.0.2"
http-types= "2.11.1"
smol-timeout= "0.6.0"
serde_with= "1.9.4"
colored= "2.0.0"
tabwriter={ version = "1.2.1", features = ["ansi_formatting"] }
hex= "0.4.3"
once_cell = "1.8.0"
getrandom = "0.2.3"
format_num= "0.1.0"
thiserror="1"