[package]
name = "melwallet-client"
version = "0.1.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# tmelcrypt = { git = "https://github.com/themeliolabs/themelio-core" }
tmelcrypt="0.1"
smolscale="0.2"
themelio-stf="0.2"
serde={version="1", features=["derive"]}
anyhow="1"
tracing-subscriber = "0.2.16"
log="0.4"
tracing="0.1"
smol="1"
serde_json= {version="1.0.64", features=["arbitrary_precision"]}
structopt="0.3"
async-h1="2.3.2"
http-types="2.11.1"
smol-timeout="0.6"
serde_with="1.9"
colored="2"
tabwriter={version="1", features=["ansi_formatting"]}
hex="0.4"